### ISSUE TITLE
Do not use alert... Never...

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#10]
Use the dialog component instead of alert and please add a better label : "Are you sure you want to delete this board ? Note that this action cannot be undone."

<img width="988" alt="screen shot 2016-05-30 at 13 42 23" src="https://cloud.githubusercontent.com/assets/5302702/15648678/68174db8-266c-11e6-9350-75350729cd53.png">

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15815488/b61dbf5e-2bcd-11e6-8296-d2bb05189914.png)

Done

**Comment by thomaswinckell** [comment]
"This action cannot be undone" should not be the title of the dialog. Read this article : https://uxplanet.org/5-essential-ux-rules-for-dialog-design-4de258c22116

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15820211/58fa223e-2be8-11e6-9565-b9f67c004f3c.png)

I changed the title and the message of the dialog. I also set it as a modal-dialog so the user cannot dismiss the dialog without make a choice
