### ISSUE TITLE
Board form

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#11]
This form should be part of the header and its position should be absolute. It should overflow the main content.

Please also add space between inputs and add some styles to the button to make it looks like a button :-)

<img width="1404" alt="screen shot 2016-05-30 at 13 45 36" src="https://cloud.githubusercontent.com/assets/5302702/15648735/d53695d4-266c-11e6-8a6b-48c34b1d2baa.png">

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15816989/f7a376d2-2bd5-11e6-87f7-375fef43780d.png)

I chose to put the form into a Dialog, it makes more sense than a form poping up into the header

**Comment by thomaswinckell** [comment]
The form could have pop from the header like a modal, but without a layer with opacity in background. I will try to find an example.

Anyway, the description should be a textarea, and please, reduce the max width of the dialog and center the fields.

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15820770/d55b4134-2beb-11e6-99bc-dc4871ac4f2b.png)

I reduce the max-width of the modal from 768px to 500px, put the TextField to fullWidth and the description Textfield is now a MultiLine Textfield (which is a TextArea)

**Comment by CremAlex** [comment]
After the modifications you've made to include your form validator into addForm I've seen a bug where error messages where not translated. It was a bug of react which was fixed in v15.2.1 launched 3 days ago.

So I upgraded react to the latest version.
