### ISSUE TITLE
No inline style

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#16]
Please never use inline style. Put your style in a different file, and import it in your JS file.

See css modules : https://github.com/css-modules/css-modules

**Comment by CremAlex** [comment]
Actually the team behind Material-ui chose to use inline Style for their lib. 

This means when I try to use `className={styles.SubmitButton}` the output is 
![image](https://cloud.githubusercontent.com/assets/5360522/15740754/a965e396-28b6-11e6-9817-6221fe85df67.png)

My style from my scss file doesn't overwrite the style from the material-ui's component

We can hack it by using `!important` but ... you know :-)

There is some issues on Github where they're discussing about it : https://github.com/callemall/material-ui/issues/4066

or this presentation : http://slides.com/kof/javascript-style-sheets#/

So I am really wondering if putting everything into stylesheet is a smart choice.

**Comment by thomaswinckell** [comment]
That's why I prefer to do the style myself or use flexible libraries...  If you copy/paste their example it is great but if you want to do something else it's not always possible...

So, yes, we can close this issue, and use inline style, but, you can put your style in an other file anyway.
