### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#2]
Please put a loader with a transparent background.

You can find good css loaders here : http://cssload.net/

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15817203/33b9df20-2bd7-11e6-9c5d-aead07be6c74.png)

Change the loader for the one used in sfeir.com

**Comment by thomaswinckell** [comment]
Good, now please center it or at least add some margin top.
