### ISSUE TITLE
Use context to translate into strings and not React Element

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#20]
Instead of this 

`<FormattedMessage {...translations.formDescriptionInputPlaceholder}>
                {DescriptionInputText => (
                    <input type="text" placeholder={DescriptionInputText} />
                )}`

Use this : 

`<input type="text" placeholder={ this.context.intl.formatMessage( translations.formDescriptionInputPlaceholder ) } />`

You will find an example on the AddBoard component

**Comment by CremAlex** [comment]
I got an issue with this. In my stores (which don't extend React.Component) I cannot access context either use the jsx syntax ... I'll have to find another way to translate messages put into the stores :/

**Comment by thomaswinckell** [comment]
Why the fuck would you translate something in a store ? A store do not render anything. 
If you are thinking about pushing a notification from a store, just send the translation key to the notification component and do the translation in that component.

**Comment by CremAlex** [comment]
Yup I just thought about this after writing this message. It's friday afternoon I'm tired :P
