### ISSUE TITLE
Show users connected on a board in card's header

### ISSUE THREAD

**Issue by CremAlex** [thomaswinckell/reactfire-white-board-website#22]
![image](https://cloud.githubusercontent.com/assets/5360522/15860314/d4a4edf2-2cc8-11e6-9759-1ca3c63bf26e.png)

I added a list of Avatar using google profile picture to show guys connected on a board. 

After 5 or more people I chose to put only one Avatar which the number of people on with a tooltip to display the name of who's on.

![image](https://cloud.githubusercontent.com/assets/5360522/15860523/bc1c783a-2cc9-11e6-8326-f83000c71ec0.png)

**Comment by thomaswinckell** [comment]
Nice ! 

Now, we need a user icon or something else to show that the number "5" means 5 online users. 
What I suggest to you is to put the images of the 5 first connected people, and then put something like "and 10 more", and when you hover, show the list of users like you do (with a bit of style please), and if you have more than 20 people, just put "and 10 more" like you see on facebook stories :

<img width="294" alt="screen shot 2016-06-07 at 4 23 41 pm" src="https://cloud.githubusercontent.com/assets/5302702/15861176/0fc9e65a-2ccc-11e6-8d5d-84b090b515ac.png">

**Comment by CremAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15888701/40f47aa0-2d68-11e6-94be-b24bd15d4bb9.png)

This my second iteration. Tell me if you see others way to improve it :-)

**Comment by thomaswinckell** [comment]
Nice ! That's what I wanted !

The "12+" needs to have more margin left and more padding (maybe put a lower font size ).
I would prefer if the tooltip was under the images and not to the right.
