### ISSUE TITLE
Board type

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#25]
A board can now have a type. In fact, a board type is just a a board with a subset of elements. It is just a restriction. See the example in comments on the whiteboard.

So, now, I want a select box in the form to add a board, to select a board type. By default, it will be free, with all the widgets. The board types will be in a configuration file.

**Comment by CremAlex** [comment]
I've made a select box to choose a type when creating a new board. I'm importing the list of widgets from the module but now I am facing a translation problem. I will need to import aswell the translation names from the module.

So my question is how should I import them? 

spliting messages.json and fr.json to import on the website the part I need or duplicate the translations for the website?
