### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#26]
It's the end of your internship @CremAlex so it's time to write a little user guide. 
It will be a pdf document with a few screenshots and some explanations about how to use the app.
Don't write a novel, just a few pages.

**Comment by CremAlex** [comment]
I have one question about this. English or French for the user guide?

**Comment by thomaswinckell** [comment]
English

**Comment by CremaFR** [comment]
https://docs.google.com/a/sfeir.lu/document/d/1eJ-5MlJq11ZXhbiCjKtgZqNvb_3QKmM0Kwt7dFZ3uao/edit?usp=sharing

Tell me what you think about it

**Comment by thomaswinckell** [comment]
Put it in the Readme.MD
