### ISSUE TITLE
Deployment guide

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#27]
Just write a pdf document (or markdown) with explanations about how to configure and deploy the app. Basically, you will start by how to checkout the source, configure the project and finish by how to generate a build, deploy the apps and how to know the apps are deployed.

Keep in mind that a guy that have never heard of the app should be able to deploy it. Usually it's not the developers that deploys apps, it's the ops guys, and they don't have time to care about your apps.

**Comment by CremAlex** [comment]
As I was writing this guide I was wondering if all the keys and url (to firebase and the proxy) should be extracted to a different place. 

I've made the deployment guide into the readme. I tested from a clean install and it works... only because all our config is in this package.json
