### ISSUE TITLE
Menu for switch language

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#5]
Put flags icon at the right side of the label.

<img width="92" alt="screen shot 2016-05-30 at 13 30 12" src="https://cloud.githubusercontent.com/assets/5302702/15648405/a9b57b16-266a-11e6-81d2-9ce05101fc55.png">

You can generate flags in css from this site : https://www.flag-sprites.com/

**Comment by CremAlex** [comment]
![gif](https://cloud.githubusercontent.com/assets/5360522/17693673/657c33a4-63a0-11e6-9967-3f69ce928429.gif)

Generated with flag-sprites
