### ISSUE TITLE
Create board form should not be displayed when loading

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#9]
When loading boards, we should not see the create board form.

<img width="624" alt="screen shot 2016-05-30 at 13 39 59" src="https://cloud.githubusercontent.com/assets/5302702/15648621/0deadbde-266c-11e6-8dc8-e043ba913299.png">

**Comment by CremAlex** [comment]
Fix with the new way to add a board see #11
